server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: faculty-profile-management
  
  datasource:
    url: jdbc:postgresql://localhost:5432/faculty_profile_db
    username: ${DB_USERNAME:faculty_user}
    password: ${DB_PASSWORD:faculty_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:ssnitfacultysystem@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-very-secure-secret-key-1234567890-ssn-faculty-system}
  expiration: 86400000 # 24 hours in milliseconds

# File Upload Configuration
file:
  upload-dir: ${UPLOAD_DIR:./uploads}
  max-file-size: 10MB
  allowed-extensions: pdf,jpg,jpeg,png,doc,docx

# Logging Configuration
logging:
  level:
    com.ssn: DEBUG
    org.springframework.security: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/server.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:3001,https://*.vercel.app,https://faculty-profile-frontend.vercel.app}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Application Configuration
app:
  base-url: ${APP_BASE_URL:http://localhost:3000}

# Email Security Configuration
email:
  verification:
    enabled: ${EMAIL_VERIFICATION_ENABLED:true}
    expiry-hours: ${EMAIL_VERIFICATION_EXPIRY_HOURS:24}
  password-reset:
    enabled: ${EMAIL_PASSWORD_RESET_ENABLED:true}
    expiry-hours: ${EMAIL_PASSWORD_RESET_EXPIRY_HOURS:1}
  rate-limit:
    per-hour: ${EMAIL_RATE_LIMIT_PER_HOUR:10}
    per-day: ${EMAIL_RATE_LIMIT_PER_DAY:50}
    ip-multiplier: ${EMAIL_RATE_LIMIT_IP_MULTIPLIER:2}
  audit:
    retention-days: ${EMAIL_AUDIT_RETENTION_DAYS:90}
    cleanup-enabled: ${EMAIL_AUDIT_CLEANUP_ENABLED:true}
